services: 
  webserver: 
    build: 
      dockerfile: ./frontend/Dockerfile
      tags: 
        - ghcr.io/ianyeoh/slides-frontend:latest
    ports: 
      - 80:80
    depends_on:
      - backend
  backend:
    build: 
      dockerfile: ./backend/Dockerfile
      tags: 
        - ghcr.io/ianyeoh/slides-backend:latest
    ports:
      - 8000:5000
  